name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build the applications
      - uses: nhartland/love-build@v1
        with:
          app_name: 'DITG'
          love_version: '11.5'

      # Upload the built applications
      - uses: actions/upload-artifact@v4
        with:
          name: built-applications
          path: 'release'

      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*
          draft: false
          prerelease: false
