name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Build the applications
      - uses: nhartland/love-build@v1
        with:
          app_name: 'Darling in the Goland'
          love_version: '11.5'
      # Upload the built applications
      - uses: actions/upload-artifact@v4
        with:
          name: built-applications
          path: 'release'